[General]

## [Locale Settings]

HourFormat="HH:mm"
## Defaults to Locale.ShortFormat. Accepts "long" or a custom string like "hh:mm A". See http://doc.qt.io/qt-5/qml-qtqml-date.html

DateFormat="dddd, d of MMMM, yyyy"
## Defaults to Locale.LongFormat. Accepts "short" or a custom string like "dddd, d 'of' MMMM". See http://doc.qt.io/qt-5/qml-qtqml-date.html



## [Interface Behavior]

ForceLastUser=true
## Have the last user appear automatically in the username field.

ForceUsernameCapitalization=true
## Force the first letter of the username to be capitalized.

ForcePasswordFocus=true
## Give automatic focus to the password field. Together with ForceLastUser this makes for the fastest login experience. 

PasswordHideDelay=0
## If you don't like to see any character at all not even while being entered set this to 0

SoundVolume=1
## The sound volume as a coefficient, where 1 is 100% and 0 is muted.